[project]
name = "zonbugusg"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-arm64", "osx-64"]
version = "1.1"

[dependencies]
filelock = "*"
meson = ">=1.3.1"
ninja = "*"
modflow-devtools = "*"


[tasks]

# meson build for triangle
setup = { cmd = "meson setup --prefix=$(pwd) --bindir=bin", env = { PKG_CONFIG_PATH = "$CONDA_PREFIX/lib/pkgconfig" } }
build = "meson install -C"

# get ostag for system
get-ostag = { cmd = "python -c 'from modflow_devtools.ostags import get_ostag; print(get_ostag())'"} 
